name: Publish to Spacebarman.com
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.SPCBRMN_FTP_HOST }}
        FTP_USERNAME: ${{ secrets.SPCBRMN_FTP_USERNAME }}
        FTP_PASSWORD: "${{ secrets.SPCBRMN_FTP_PASSWD }}"
        REMOTE_DIR: ${{ secrets.SPCBRMN_FTP_DIR }}
        ARGS: --delete
        # --delete arg will delete files on the server if you've deleted them in git
